### ISSUE TITLE
Request: Longer Textfield for quickMove/quickJump

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#378]
Unfortunately the field size of quickMove/quickJuno field is very short. Often it is not possible to see, what the field completely refers to and it it is necessary to retype and select the wanted folder again.

... SomeLongName/Subfolder02. Even harder for e.g. SomeVeryLongName/Subfolder02/SubSubfolder03

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/ae9859c2-fe59-4224-a1e0-1c8310102aac)

Can you please enlarge the field? It is no problem to me (and perhaps other people), if the field overlay the tabs next to it instead of moving them to the right. Marvelous, if you introduce some options to set (e.g. width of field, above/below tabs, ...), so each one can define how it fits best for the personal use.

**Comment by RealRaven2000** [comment]
Just to add this workaround here it is possible to get at all subfolder without spelling out the complete names of folders, e.g. 

to get to Mozilla/Addons/quickFilters/Support one can enter mo/ad/qu/sup

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/2b0a933f-f0d7-41fb-890e-e30c505d9fb5)

... to skip some folders in between one can use the  `>` Operator:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/81454820-2de7-44ae-8762-0dc5ddf3d3eb)

**Comment by RealRaven2000** [comment]
Here is a resource on how this could be achieved:

https://css-tricks.com/auto-growing-inputs-textareas/

The trick is to use a container that grows with the entered text, and the text needs to be added to the content of the container via an event using the dataset attribute:

```html
  <label class="input-sizer stacked">
    <span>Text: </span>
    <textarea oninput="this.parentNode.dataset.value = this.value" rows="1" placeholder="hi"></textarea>
  </label>
```

```css
.input-sizer {
  display: inline-block;
  position: relative;
  width: fit-content;
  min-width: 9em;
  height: 1.8em;
  border: solid 1px;
  padding: .25em .5em;

  input {
    position: absolute;
    top:0;
    left:0;
    width:100%;
    height:100%;
    font: inherit;
    padding: inherit;
    margin:0;
    appearance: none;
    border: none;
  }
}

.input-sizer::after {
  content: attr(data-value) ' ';
  visibility: hidden;
}
```
