### ISSUE TITLE
Unwanted text shadow in quickJump help panel

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#427]
In dark themes we see that the help text that is displayed in a panel once the blue help icon to right is clicked, has unwanted text shadows:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/b729d0c3-a670-4ff4-9626-f53d87a7f8e5)

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/73e83d59-1770-4162-846b-07b9794f8f99)

This is caused by a browser rule in global-shared.css:

```css
/* Lightweight theme roots */

:root[lwtheme-image] {
  text-shadow: 0 -0.5px 1.5px white;
}
```
